---
date: "2019-05-05T00:00:00+01:00"
draft: false
linktitle: Math & R Appendices
menu:
  resources:
    parent: Resources
title: List of Math & R Appendices
toc: true
type: docs
weight: 2
---

# List of Math and R Appendices

The following list contains links to all appendices spread across the [Class Content](/content) pages:

| Appendix         | Type | Class |
|------------------|------|------:|
| Installing R and R Studio | R | [1.2 class](https://metricsf21.classes.ryansafner.com/content/1.2-content/#installing-r-and-r-studio) |
| R Packages | R | [1.2 class](https://metricsf21.classes.ryansafner.com/content/1.2-content/#r-packages) |
| Getting Help for R | R | [1.2 class](https://metricsf21.classes.ryansafner.com/content/1.2-content/#other-useful-commands-to-know) |
| Other Useful Commands to Know | R | [1.2 class](https://metricsf21.classes.ryansafner.com/content/1.2-content/#other-useful-commands-to-know) |
| Suggested Style Guide for Coding | R | [1.2 class](https://metricsf21.classes.ryansafner.com/content/1.2-content/#suggested-style-guide-for-coding) |
| The Summation Operator | Math/Stats | [2.1 class](https://metricsf21.classes.ryansafner.com/content/2.1-content/#the-summation-operator) |
| Useful Properties of Summation Operators | Math/Stats | [2.1 class](https://metricsf21.classes.ryansafner.com/content/2.1-content/#useful-properties-of-summation-operators) |
| Useful Properties for Regression | Math/Stats | [2.1 class](https://metricsf21.classes.ryansafner.com/content/2.1-content/#useful-properties-for-regression) |
| Properties of Expected Value and Variance | Math/Stats | [2.2 class](https://metricsf21.classes.ryansafner.com/content/2.2-content/#properties-of-expected-value-and-variance) |
| Graphing Mathematical Functions | R | [2.2 class](https://metricsf21.classes.ryansafner.com/content/2.2-content/#graphing-mathematical-functions) |
| Bult-in Statistical Functions | R | [2.2 class](https://metricsf21.classes.ryansafner.com/content/2.2-content/#bult-in-statistical-functions) |
| Graphing Statistical Functions | R | [2.2 class](https://metricsf21.classes.ryansafner.com/content/2.2-content/#graphing-statistical-functions) |
| Variance, Covariance, and Correlation | Math/Stats | [2.3 class](https://metricsf21.classes.ryansafner.com/content/2.3-content/#variance) |
| Deriving the OLS Estimators | Math/Stats | [2.4 class](https://metricsf21.classes.ryansafner.com/content/2.4-content/#deriving-the-ols-estimators) |
| Algebraic Properties of OLS Estimators | Math/Stats | [2.4 class](https://metricsf21.classes.ryansafner.com/content/2.4-content/#algebraic-properties-of-ols-estimators) |
| Bias in $\hat{\beta_1}$ | Math/Stats | [2.4 class](https://metricsf21.classes.ryansafner.com/content/2.4-content/#bias-in-hatbeta_1) |
| Proof of the Unbiasedness of $\hat{\beta_1}$ | Math/Stats | [2.4 class](https://metricsf21.classes.ryansafner.com/content/2.4-content/#proof-of-the-unbiasedness-of-hatbeta_1) |
| Robust Standard Errors in R | R | [2.5 class](https://metricsf21.classes.ryansafner.com/content/2.5-content/#robust-standard-errors-in-r) |
| Differences Between What We Learned in Class and Classical Statistics | R | [2.6 class](https://metricsf21.classes.ryansafner.com/content/2.6-content/#differences-between-what-we-learned-in-class-and-classical-statistics) |
| T-Test for Difference in Group Means | Math/Stats | [3.6 class](https://metricsf21.classes.ryansafner.com/content/3.6-content/#appendix-t-test-for-difference-in-group-means) |
| Marginal Effects for Two-Continuous Variable Interactions | Math/Stats | [3.7 class](https://metricsf21.classes.ryansafner.com/content/3.7-content/#appendix-marginal-effects-for-two-continuous-variable-interactions) |