---
title: "Assignments Overview"
---

On this page, you can find more information about each individual assignment, as well as the assignments themselves.

-   [<i class="fas fa-calculator"></i> `Grade Calculator`](https://ryansafner.shinyapps.io/480_grade_calculator/)

Use this tool to help calculate your overall course grade using existing assignment grades, as well as forecast "what if" scenarios.

Please refer to the [syllabus](/syllabus) for more information about grades.

## Short Papers

There will be two short papers on assigned topics. The first will be early in the semester, covering topics from the first several weeks. The second will cover topics from the remaining weeks. I am looking for 3-5 page papers that explore subjects prompted by questions that I will provide to you in advance. However, I also encourage you to take the less-trodden path and explore something unique and interesting to you.

## Term Paper

Each of you will write a term paper tracing and critically discussing the intellectual history of an economic topic of your choice. This assignment will be scaffolded so that certain sections of the paper are due partway through the semester so that I can provide feedback for you to incorporate into the final draft. More information will be provided in class.