---
title: "Participation and Discussion"
---

Every week, we will have a discussion board thread on Blackboard. You will be expected to contribute to the discussion board at least twice in the week. Your weekly contribution will be graded out of 5 points. At the end of the semester, I will apply the *average* of your weekly participation grades to apply (40%) towards your final course grade. 

I am interested in your thoughts, reactions, comments, and questions about any of the material (lectures and/or readings). You do not need to write more than a paragraph. Anything more than that, including continuing to reply to each others’ thoughts, questions, or comments, (which I strongly hope you do!) is solely based on your own interest and curiosity. I will jump in to answer questions the group is stuck on, give my two cents, and stir the pot as needed. I strontly hope we still keep a conversation going and can learn from each other, that was always my goal, not to lecture at you! If you crave visual human contact, you can submit your comments/reactions in the form of a short video, and we can try that out! Though we might eventually need to move beyond Blackboard in that case. We’ll see how things go.

Rubric:

| Category | 3 Points | 2 Points | 1 Point | 0 points |
|----------|----------|----------|---------|----------|
| Quantity | More than 2 replies/started threads | 2 replies/started threads | 1 reply | 0 posts |
| Quality | Extremely thought provoking, demonstrates clear grappling with readings, adds to conversation | Provides a well-reasoned reply, suggests familiarity with readings, keeps conversation going | A simple reply, may make no reference to readings or ideas, makes further conversation difficult | Minimal effort |

Recall, these are out of 5 points. Notice it is possible to get above 5 points for a truly remarkable week of contributions, but I give these sparingly.

At the end of the semester, I will drop your lowest participation score.
